name: My Flutter Workflow

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_version: '3.22.3'
      test_recursion: true
      coverage_excludes: '*.g.dart *.gr.dart *.config.dart *.freezed.dart'
      min_coverage: 90
